language: php

php:
  - 5.4
  - 5.5
  - 5.6
matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.4.*
    - php: 5.5
      env: SYMFONY_VERSION=2.5.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master
before_script:
  - composer self-update
  - composer install --dev

script: phpunit --coverage-text

notifications:
  email:
    - fort.pierrelouis@gmail.com